# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0011_merge_20191212_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SQLGlobalAppConfig',
            new_name='GlobalAppConfig',
        ),
    ]
